### ISSUE TITLE
how to mark point on the three images correctly

### ISSUE THREAD

**Issue by SriRamGovardhanam** [ankesh007/Body-Measurement-using-Computer-Vision#4]
E:\opencvdemo>python code.py -i1 C:\Users\ASUS\Desktop\final_saket1.jpg -i2 C:\Users\ASUS\Desktop\final_saket2.jpg -i3 C:\Users\ASUS\Desktop\final_saket3.jpg -a false
(2268, 4032, 3)
(2268, 4032, 3)
waist 350.0494518583487
Traceback (most recent call last):
  File "code.py", line 425, in <module>
    main()
  File "code.py", line 421, in main
    metre_pixel_y)
  File "code.py", line 345, in measure_distance
    right_shoulder_lambda)
  File "code.py", line 281, in detect_point_and_ask_user
    left = detector_fn_lef(segmented_img, head_point_left[0], head_point_left[1])
  File "code.py", line 321, in <lambda>
    left_shoulder_lambda = lambda img, point0, point1: first_sharp_fall(img, point0, point1, -20, 1.5)
  File "code.py", line 201, in first_sharp_fall
    y0 = np.nonzero(mask[:, x_curr])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

this is what i got the output
i think it goes wrong with marking the points on images
can i get more information on how to input those dots/marks on images correctly

**Comment by ankesh007** [comment]
You just have to click the relevant points. The description of what point to mark in which image is mentioned in README.

**Comment by shantanu848** [comment]
> You just have to click the relevant points. The description of what point to mark in which image is mentioned in README.

Please can you elaborate a bit more. I am having issue In marking too.

**Comment by Rehmani-commits** [comment]
plz tell us @sirankesh007
how to run the code 
when i am running the code  the output is only show the images 
tell me how to get the result of measuring shoulder and waiste
