### ISSUE TITLE
re-run cmake or configure script in function cvSetMouseCallback

### ISSUE THREAD

**Issue by sangramrajekakade** [ankesh007/Body-Measurement-using-Computer-Vision#5]
I got this issue, can you provide **requirements.txt**

```
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvSetMouseCallback, file /io/opencv/modules/highgui/src/window.cpp, line 578
Traceback (most recent call last):
  File "code2.py", line 399, in <module>
    main()
  File "code2.py", line 374, in main
    metre_pixel_x,metre_pixel_y,coordinate,affine_correct_parameters=analyze_chessboard(image,affine_correct_flag)
  File "code2.py", line 228, in analyze_chessboard
    cv2.setMouseCallback(window_name1, click_and_crop)
cv2.error: /io/opencv/modules/highgui/src/window.cpp:578: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvSetMouseCallback

```

**Comment by ankesh007** [comment]
Unfortunately, I do not have the environment where I did this development. I think simple googling this error shows many solutions. Hope you are able to resolve it.
